### ISSUE TITLE
Server disconnects players with DecoderException on login

### ISSUE THREAD

**Issue by spiritedfang** [JoeFoxe/Hexerei-1.18#4] opened 2021-12-21 21:58 UTC
**Versions**
Minecraft 1.18.1 (Forge 39.0.7)
Hexerei 0.1.8

**Summary**
So, this one is a little weird since there are no client or server logs (just a screenshot of the error). Players are being disconnected on login when Hexerei is installed with an internal exception that's different every time. I provided a screenshot below ("non [a-z0-9/._-] character in path of location"). This happens even if Hexerei is the only mod on the client and server.

![image](https://user-images.githubusercontent.com/12414663/147002785-b41b1be6-ccb3-47e0-b0f7-d8522e0b923f.png)

**Comment by JoeFoxe** [comment] 2021-12-22 02:38
This definitely seems like its not a bug due to my mod. I have nothing to do with a stonecutter and copper slabs. I would say try reinstalling forge or something. I have never come across anything like this before

**Comment by JoeFoxe** [comment] 2021-12-22 04:22
I could be wrong about this though... I will look into it

**Comment by JoeFoxe** [comment] 2021-12-22 04:37
I am definitely wrong and am sorry, this is to do with my mod and will try to solve this asap!

**Comment by JoeFoxe** [comment] 2021-12-22 07:23
This issue will be fixed in the next update. coming sometime tomorrow - Thanks for letting me know!

**Closed by JoeFoxe** 2021-12-22 07:23 UTC

**Comment by spiritedfang** [comment] 2021-12-22 18:53
Well, this was just with Hexerei installed and nothing else. The item in the error is different each time. Here's how I reproduce it without fail:

1. Create a new Forge server (version 39.0.7).
2. Create a new Forge client (version 39.0.7, new profile in CurseForge).
3. Add the Hexerei mod to both.
4. Run the server (generating a new world) and run the client.
5. Attempt to connect to the server from the client (repeatable).

Not sure if this helps, but I'm running the server on Linux. Could it possibly be a problem with text encoding a path or the en-us locale of my server? Thanks for your time.

**Comment by spiritedfang** [comment] 2021-12-22 18:54
Whoops! The rest of the comments just loaded in. For some reason I only saw the first. Thanks again for your time - really appreciated. ✌️
